### ISSUE TITLE
Testing with low- or no-overlap point clouds for part assembly

### ISSUE THREAD

**Issue by ttsesm** [ZhileiChen99/UTOPIC#2]
Hi @ZhileiChen99,

Congrats for your work and thank for making it publicly available. I have a question regarding your work, do you think that it would work for really low- or no-overlap point clouds for part assembly? For example there is a recent published benchmark and dataset for part assembly called [Breaking bad ](https://breaking-bad-dataset.github.io/). This dataset features mainly point clouds of objects with no overlap and for which they try to assembly all together.

So I was curious to check whether your approach could be interesting to be used for this task. I would appreciate any feedback.

Thanks.

**Comment by ZhileiChen99** [comment]
I think this work can solve the low-overlapping registration problem well, but if you need to adopt it to large-scale scenes, maybe you should add the sampling module. However, for extremely low-overlapping or no-overlapping point clouds, this work may fail to register them.

**Comment by ZhileiChen99** [comment]
I think this work can solve the low-overlapping registration problem well, but if you need to adopt it to large-scale scenes, maybe you should add the sampling module. However, for extremely low-overlappng or no-overlapping point clouds, this work may fail to register them.

**Comment by ttsesm** [comment]
I see, thanks for the feedback.
